name: my_first_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  vibration: ^3.1.3
  flutter:
    sdk: flutter
  record: ^4.0.0
  sqflite: ^2.0.0+4
  system_info2: ^4.0.0
  battery_plus: ^6.0.2
  open_file: ^3.3.2
  network_info_plus: ^6.0.0
  flutter_speedtest: ^0.2.0
  pdf: ^3.11.1
  flutter_media_info: ^0.0.3
  clipboard: ^0.1.3
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.6
  webview_flutter_wkwebview: ^3.14.0
  permission_handler: ^11.3.1
  battery_info: ^1.1.1
  fluttertoast: ^8.0.8
  sensors_plus: ^6.0.1
  path_provider: ^2.1.4
  device_info_plus: ^10.1.2
  device_apps: ^2.2.0
  installed_apps: ^1.5.0
  path: ^1.8.0
  intl: ^0.19.0
  url_launcher: ^6.1.7
  mockito: ^5.0.16
  build_runner: ^2.1.7
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/ru.json
    - assets/device_info.json
    - assets/fonts/Roboto-Regular.ttf
    - assets/images/app_logo.png    